name: Docker-Images
on:
  push:
    tags:
      - "*"

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dotnet 8.0.100
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.100
          include-prerelease: True

      - name: Setting Version
        id: vars
        run: echo ::set-output name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      # docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 设置 docker 环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # build 并且 push docker 镜像
      - name: Push Lion.AbpPro.HttpApi.Host Image
        uses: docker/build-push-action@v2
        with:
          context: aspnet-core
          push: true
          tags: zzzwangjun/lion.abp.pro:${{ steps.vars.outputs.RELEASE_VERSION }}

  vben28:
    runs-on: ubuntu-latest
    needs: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Setting Version
        id: vars
        run: echo ::set-output name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      # docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 设置 docker 环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # build 并且 push docker 镜像
      - name: Push Vue3 Image
        uses: docker/build-push-action@v5
        with:
          context: vben28
          push: true
          tags: zzzwangjun/lion.abp.pro.vben28:${{ steps.vars.outputs.RELEASE_VERSION }}
